Explicitly decode the home directory file name returned by os.path.expanduser from the file system encoding. os.path.expanduser doesn't do it, and so causes a UnicodeDecodeError if the home directory name contains non-ASCII characters and the file system encoding differs from the default system encoding. This has only been a problem on Windows where the file system encoding is some "mbcs" thing. On Unix it would be a problem except that PyGTK silently changes the system encoding to "UTF-8" from "ascii" when it is imported, and UTF-8 is likely to be the file system encoding.
The error looked like this (with many variations):
Traceback (most recent call last):
  File "zenmap", line 97, in <module>
  File "zenmapGUI\App.pyo", line 39, in <module>
  File "zenmapCore\UmitConf.pyo", line 27, in <module>
  File "zenmapCore\Paths.pyo", line 32, in <module>
  File "zenmapCore\BasePaths.pyo", line 28, in <module>
  File "ntpath.pyo", line 368, in expanduser
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 28: unexpected code byte