Fix compile error on windows: .\ncat_exec_win.c(411) : error C2660: 'fix_line_endings' : function does not take 3 arguments call was missing 'state' parameter.