Fix a Zenmap crash when trying to compare two files, either one of which has more than one extraports element. The crash looked like
TRACEBACK:
Traceback (most recent call last):
  File "/usr/local/lib/python2.5/site-packages/zenmapGUI/DiffCompare.py", line 378, in refresh_diff
    self.compare_view.make_diff(parsed1, parsed2)
  File "/usr/local/lib/python2.5/site-packages/zenmapGUI/DiffCompare.py", line 751, in make_diff
    self.add_host_diff(host_state, host, second_host)
  File "/usr/local/lib/python2.5/site-packages/zenmapGUI/DiffCompare.py", line 802, in add_host_diff
    self.add_extraports_diff(parent, "", extraports1, extraports2)
  File "/usr/local/lib/python2.5/site-packages/zenmapGUI/DiffCompare.py", line 906, in add_extraports_diff
    self.diff_it(parent, "", _("Count"), extraports1.get("count"),
AttributeError: 'list' object has no attribute 'get'