Add changes to the openssl package to macports-1.7.0-universal.diff. This makes OpenSSL link against the 10.4u SDK. Previously it linked against the 10.5 SDK, which I believe was the cause of another crash on 10.4. The crash looked like
Error in sys.excepthook: 
Traceback (most recent call last): 
  File "/Applications/Zenmap.app/Contents/Resources/zenmap.py", line 70, in excepthook 
    from zenmapGUI.CrashReport import CrashReport 
  File "zenmapGUI/CrashReport.pyc", line 35, in <module> 
  File "zenmapCore/BugRegister.pyc", line 23, in <module> 
  File "urllib2.pyc", line 91, in <module> 
  File "hashlib.pyc", line 133, in <module> 
  File "hashlib.pyc", line 60, in __get_builtin_constructor 
ImportError: No module named _md5