Change -PN to -Pn in get_option_check_auxiliary_widget. It turns out this bit of code has to be kept in sync with profile_editor.xml when a new option_check is added. We got an anonymous Zenmap crash report from this.
  File "/usr/local/lib/python2.5/site-packages/zenmapGUI/OptionBuilder.py", line 125, in get_option_check_auxiliary_widget
    assert False, "Unknown option %s" % option
AssertionError: Unknown option -Pn